function interfataFTB(R,C)
%fereastra principala----------------------------------------------------
figure('Name','Filtru trece banda',... 
       'Units','normalized',...
       'Color', [0.8, 0, 0.5560],...
       'NumberTitle','off');

uicontrol('Style','text',...
             'Units','normalized',...
             'Position',[0.54 0.93 0.36 0.05],...
             'backgroundcolor','w',...
             'foregroundcolor',[0.4940 0.1840 0.5560],...
             'FontSize',14,...
             'String',' Filtrul trece banda');
         
%fereastra cu parametrii--------------------------------------------------
uibuttongroup('Visible','on',...
              'BackgroundColor','w',...
              'ForegroundColor',[0.4940 0.1840 0.5560],...
              'FontSize',14,...
              'FontWeight','b',...
              'TitlePosition','centertop',...
              'Title','PARAMETRI',...
              'Position',[0.02 0.70 0.28 0.25]);
%rezistenta
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.07 0.81 0.10 0.05],...
          'BackgroundColor','w',...
          'ForegroundColor','r',...
          'FontSize',12,...
          'FontWeight','b',...
          'String',' R  [ ohm ]');

uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.19 0.81 0.05 0.05],...
          'BackgroundColor','w',...
          'ForegroundColor','k',...
          'FontSize',12,...
          'String',R,...
          'Callback','R=str2num(get(gco,''String''));close;interfataFTB(R,C)'); %gco - returneaza obiectul curent
                                                                         
%capacitatea
uicontrol('Style','Text',...
           'Units','Normalized',...
           'Position',[0.07 0.74 0.10 0.05],...
           'BackgroundColor','w',...
           'ForegroundColor','r',...
           'FontSize',12,...
           'FontWeight','b',...
           'String',' C  [ F ]');

uicontrol('Style','Edit',...
           'Units','Normalized',...
           'Position',[0.19 0.75 0.05 0.05],...
           'BackgroundColor','w',...
           'ForegroundColor','k',...
           'FontSize',12,...
           'String',C,...
           'Callback','C=str2num(get(gco,''String''));close;interfataFTB(R,C)');

%afisarea imaginii--------------------------------------------------------
       subplot('Position',[0.01 0.06 0.3 0.27]);
     im = imread('trece_banda_schema.JPG');
imshow(im);

% Adăugarea unui grup de butoane checkbox pentru culoare------------------
colorCheckboxGroup = uibuttongroup('Visible', 'on',...
                                   'BackgroundColor', 'w',...
                                   'ForegroundColor', [0.4940 0.1840 0.5560],...
                                   'FontSize', 12,...
                                   'FontWeight', 'b',...
                                   'TitlePosition', 'centertop',...
                                   'Title', 'Culoare Grafice',...
                                   'Position', [0.31 0.54 0.15 0.10]);

% Adăugarea butoanelor checkbox pentru culori
    uicontrol(colorCheckboxGroup, 'Style', 'checkbox',...
              'String', 'Albastru deschis',...
              'Units', 'normalized',...
              'Position', [0.05 0.6 0.9 0.3],...
              'Callback', @(src,event) updateGraphColor(src,'cyan'));

    uicontrol(colorCheckboxGroup, 'Style', 'checkbox',...
              'String', 'Verde',...
              'Units', 'normalized',...
              'Position', [0.05 0.2 0.9 0.3],...
              'Callback', @(src,event) updateGraphColor(src,'green'));



% Funcția de callback pentru butoanele checkbox
function updateGraphColor(src, color)
    % Verificăm dacă checkbox-ul este bifat sau nu
    if src.Value
        % Setăm culoarea graficelor în funcție de butonul checkbox selectat
        subplot('Position', [0.48 0.65 0.5 0.23]);
        semilogx(f, gain, color, 'linewidth', 3);
        grid on;
        xlabel('Frecventa,Hz'); ylabel('Amplitudine, dB');
        subplot('Position', [0.48 0.30 0.5 0.23]);
        semilogx(f, phase, color, 'linewidth', 3);
        grid on;
        xlabel(['Frecventa, Hz',' f0= ', num2str(f0)]); ylabel('Faza,grade');
    else
        
    end
end




% Adăugarea unui meniu pop-up---------------------------------------------
popupMenu = uicontrol('Style', 'popupmenu',...
                      'Units', 'normalized',...
                      'Position', [0.35 0.15 0.07 0.05],...
                      'BackgroundColor', 'white',...
                      'String', {'Selecteaza', 'Functia de transfer', 'Frecventa', 'Pulsatia'},...
                      'FontSize', 12,...
                      'Callback', @(src, event) popupMenuCallback(src, event, R, C));
                      

% Funcția de callback pentru meniul pop-up
function popupMenuCallback(src, event, R, C)
selectedOption = popupMenu.Value;
        switch selectedOption
            case 2
                % Afiseaza imaginea corespunzatoare pentru "Functia de transfer"
                im = imread('functia_de_transfer.JPG');
                subplot('Position', [0.45 0.06 0.3 0.15]);
                imshow(im);
            case 3
                % Afiseaza imaginea corespunzatoare pentru "Frecventa"
                im = imread('frecventa.JPG');
                subplot('Position', [0.45 0.06 0.3 0.15]);
                imshow(im);
            case 4
                % Afiseaza imaginea corespunzatoare pentru "Pulsatie"
                im = imread('pulsatia.JPG');
                subplot('Position', [0.45 0.06 0.3 0.15]);
                imshow(im);
            otherwise
       end
end

%Fereastra de calcule-----------------------------------------------------
w=logspace(1,9,100);
num= 1i*w*R*C; den = -w.^2.*R.^2*C.^2 + 3*R*C*1i*w + 1;


h=abs(num./den);

%calculul castigului
gain=20*log10(h);

%calculul frecventei in functie de w (declarata mai sus)
f=w/(2*pi);
%calculul fazei semnalului
                phase=angle(num./den)*180/pi;
     f0=1./(2.*pi.*R.*C);
     Q=1./3;
     fmin=f0*(sqrt(1+4*Q.^2)-1)/(2*Q);
     fmax=f0*(sqrt(1+4*Q.^2)+1)/(2*Q);
     BandaFrecv=fmax-fmin;

uibuttongroup('Visible','on',...
              'BackgroundColor','w',...
              'ForegroundColor',[0.4940 0.1840 0.5560],...
              'FontSize',15,...
              'FontWeight','b',...
              'TitlePosition','centertop',...
              'Title','CALCULE',...
              'Position',[0.02 0.35 0.28 0.28]);
  
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.07,0.5,0.15,0.05],...
          'BackgroundColor','w',...
          'ForegroundColor','r',...
          'FontSize',14,...
          'FontWeight','b',...
          'String',[' f0 = ',num2str(fix(f0)),' Hz ']);
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.07,0.46,0.15,0.05],...
          'BackgroundColor','w',...
          'ForegroundColor','r',...
          'FontSize',15,...
          'FontWeight','b',...
          'String',['fmax = ',num2str(fix(fmax)),' Hz ']); 
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.07,0.42,0.15,0.05],...
          'BackgroundColor','w',...
          'ForegroundColor','r',...
          'FontSize',15,...
          'FontWeight','b',...
          'String',['fmin = ',num2str(fix(fmin)),' Hz ']); 
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.07,0.38,0.15,0.05],...
          'BackgroundColor','w',...
          'ForegroundColor','r',...
          'FontSize',15,...
          'FontWeight','b',...
          'String',['Bf = ',num2str(fix(BandaFrecv)),' Hz ']); 
           
      
 %grafice---------------------------------------------------------
 subplot('Position', [0.48 0.65 0.5 0.23]);
    semilogx(f,gain,'b','linewidth',3);
    grid on;
    xlabel('Frecventa(Hz)');ylabel('Amplitudine(dB)');
subplot('Position', [0.48 0.30 0.5 0.23]);
    semilogx(f,phase,'b','linewidth',3);
    grid on;
    xlabel(['Frecventa(Hz)',' f0= ',num2str(f0)]);ylabel('Faza(grade)');
    grid on;
    %xlabel(['Frecventa(Hz)','  f0= ',num2str(f0)]);ylabel('Faza(grade)');
    
%buton iesire------------------------------------------------------------
 
uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.83 0.05 0.13 0.05],...
            'FontWeight','b',...
            'FontSize',14,...
            'BackgroundColor','black',...
            'ForegroundColor','w',...
            'String','I E S I R E',...
            'Callback','close');
% Meniu-----------------------------------------------------------------
  
m=uimenu('Label','Documentatie');
   uimenu(m,'Label','documentatie_gac','Callback','open(''documentatie_gac.2.pdf'')');    
 
end